/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * hi yue
 */
package nz.ac.aut.pdc.ChessHits.GUI;

import java.awt.Color;
import java.awt.GridLayout;
import nz.ac.aut.pdc.ChessHits.model.Board;
import nz.ac.aut.pdc.ChessHits.model.ChessHitsGame;
import nz.ac.aut.pdc.ChessHits.model.Player;

    // Variables declaration - do not modify                     
    // End of variables declaration                   
/**
 *
 * @author gl
 */
public class MainFrame extends javax.swing.JFrame {
 
    private ChessHitsGame game;
    private Player playerOne;
    private Player playerTwo;
    private Board board;
    private int helloYue;
    
    
    MainFrame(Player playerOne, Player playerTwo , ChessHitsGame game, boolean PlayerOneWhite) {
        this.game = game;
        this.playerOne = playerOne;
        this.playerTwo = playerTwo;
        this.board = game.getBoard();
        initComponents();
        this.setLocationRelativeTo(null);   
        setUpPanels();
        if(PlayerOneWhite){
            this.playerOne.setIsTurn(true);
              this.playerTwo.setIsTurn(false);
        }
        else{
             this.playerOne.setIsTurn(false);
             this.playerTwo.setIsTurn(true);
        }
        update();
    }
    private void update(){
        if(playerOne.getIsTurn()){
        lblPlayer.setText("playersTurn: \n"+playerOne.getName());
        lblPlayerColor.setText(playerOne.getSelectedColor().getTextRepresentation());
        }
        else{
            lblPlayer.setText("playersTurn: \n"+playerTwo.getName());
            lblPlayerColor.setText(playerTwo.getSelectedColor().getTextRepresentation());
        }
    }

    
    
    
       private void setUpPanels(){
           int row = board.getHeight();
           int col = board.getWidth();
                gamePanel.setLayout(new GridLayout(row, col));
           for(int i = 0; i < row; i++){
                for(int j = 0; j < col; j++){
                    SqurarePanel sQP = new SqurarePanel(game, i, j);
               gamePanel.add(sQP);
           }
         }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer = new javax.swing.JLabel();
        lblPlayerColor = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlayer.setText("jLabel1");

        lblPlayerColor.setText("jLabel1");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerColor)
                    .addComponent(lblPlayer))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlayerColor)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerColor;
    // End of variables declaration//GEN-END:variables
}
