/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.pdc.ChessHits.GUI;

import nz.ac.aut.pdc.ChessHits.model.Player;

/**
 *
 * @author gl
 */
public class MenuPanel extends javax.swing.JPanel {

    private Player playerOne;
private Player playerTwo;

    MenuPanel(Player playerOne, Player playerTwo) {
        initComponents();
        this.playerOne = playerOne;
        this.playerTwo = playerTwo;
        update();
    }

       public void update() {
        if (playerOne.getIsTurn()) {
            lblPlayer.setText("playersTurn: \n" + playerOne.getName());
            lblPlayerColor.setText(playerOne.getSelectedColor().getTextRepresentation());
        } else {
            lblPlayer.setText("playersTurn: \n" + playerTwo.getName());
            lblPlayerColor.setText(playerTwo.getSelectedColor().getTextRepresentation());
        }
        this.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer = new javax.swing.JLabel();
        lblPlayerColor = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPlayerColor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayerColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerColor;
    // End of variables declaration//GEN-END:variables
}
